# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Biesnecker
tagline:             '世界潮流顺之者'
description:         'Ideas and opinions about people, pleaces, and things (mostly code).'
url:                 http://biesnecker.com
baseurl:             /
paginate:            10
future:              false
safe:                false

# About/contact
author:
  name:              John Biesnecker
  url:               https://facebook.com/biesnecker
  email:             jbiesnecker@gmail.com

# Custom vars
version:             1.0.0

# Exclude
exclude:             ['publish.sh', 'push.sh']

# Gems
gems:
    - jekyll-sitemap
    - jekyll-assets

categories:
    sweiqotd:
        title: "Software Engineering Interview Question of the Day"
        description: >
            SWEIQotD is a (semi-) daily series of questions and detailed answers for the kind of questions one tends to face during software engineering interviews. It is mostly for me, but I thought it might be useful for others so I'm posting them.
