# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Biesnecker
tagline:             '世界潮流顺之者'
description:         'Ideas and opinions about people, pleaces, and things (mostly code).'
url:                 http://biesnecker.com
baseurl:             /
paginate:            10
future:              false
safe:                false

# About/contact
author:
  name:              John Biesnecker
  url:               https://facebook.com/biesnecker
  email:             jbiesnecker@gmail.com

# Custom vars
version:             1.0.0

# Exclude
exclude:             ['publish.sh', 'push.sh']

# Gems
gems:
    - jekyll-sitemap
    - jekyll-assets
